Feature/847 support multiple sort criterias
holunda-io/camunda-bpm-taskpool pull request #875
Opened 2023-09-29 10:35 UTC by MichaelVonB

Sort parameter now accepts a list of String instead. Old api (single string) is kept and marked as deprecated. 
Fixes #847

2023-10-06 15:46 UTC, zambrovski commented on view/jpa/src/main/kotlin/io/holunda/polyflow/view/jpa/SpecificationExt.kt
> +      val direction = it!!.substring(0,1)
I believe `it`is sufficient instead of `it!!`

2023-10-06 15:46 UTC, zambrovski commented on view/jpa/src/main/kotlin/io/holunda/polyflow/view/jpa/SpecificationExt.kt
> +      val field = it!!.substring(1)
same here

2023-10-06 15:53 UTC, zambrovski requested changes

2023-10-06 15:53 UTC, zambrovski commented on view/view-api/src/main/kotlin/query/PageableSortableQuery.kt
> +      val direction = it!!.substring(0, 1)
please use `it` instead of `it!!`

2023-10-06 15:53 UTC, zambrovski commented on view/view-api/src/main/kotlin/query/PageableSortableQuery.kt
> +      val parameter = it!!.substring(1)
see above

2023-10-06 15:53 UTC, zambrovski commented on view/view-api/src/main/kotlin/sort/Sorter.kt
>    if (sort.isNullOrBlank()) return null
please use curly braces even in short if statements

2023-10-06 15:53 UTC, zambrovski commented on view/view-api/src/main/kotlin/sort/Sorter.kt
> +  if (sort.isEmpty()) return null
{}

2023-10-06 15:53 UTC, zambrovski commented on view/view-api/src/main/kotlin/sort/Sorter.kt
>    if (sort.isNullOrBlank()) return null
{}

2023-10-06 15:53 UTC, zambrovski commented on view/view-api/src/main/kotlin/sort/Sorter.kt
> +  if (sort.isEmpty()) return null;
{}

2023-10-06 15:53 UTC, zambrovski commented
Looks generally good, could you fix the minor issues, please?

2023-10-10 08:00 UTC, MichaelVonB commented
Should be done. Let me know if there is anything else

2023-10-10 10:57 UTC, zambrovski approved these changes

2023-10-10 10:57 UTC, merged